### ISSUE TITLE
RST_STREAM frame error codes missing

### ISSUE THREAD

**Issue by LPardue** [quicwg/wg-materials#1]
Hi,

I believe the RST_STREAM error codes are missing from https://tools.ietf.org/html/draft-hamilton-quic-transport-protocol-01 (there weren't in the previous version either). 

These error codes are distinct from other error codes but the enumeration ranges overlap, which causes some unfortunate aliasing. I raised this issue on the QUIC Protocol discussion group (https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/dSSNpQj3shI) but also raising here to signal when the the I-D gets updated.

**Comment by mnot** [comment]
Hi,

This repo isn't for issues regarding the drafts -- we'll get that up soon. Hold tight.

**Comment by LPardue** [comment]
Sorry!
